export const SET_FRUITS = "SET_FRUITS";
export const FETCH_FRUITS_FAILED = "FETCH_FRUITS_FAILED";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";

export const CHANGE_HANDLER = "CHANGE_HANDLER";
